## Pandas Basic

[10min](http://pandas.pydata.org/pandas-docs/stable/10min.html)

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

In [7]:
dates = pd.date_range('20130101', periods=6)
print dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [12]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df.head()

A         B         C         D
2013-01-01 -0.196382 -0.272406 -0.113875  0.077248
2013-01-02 -1.094411 -0.086503  0.369065  0.080293
2013-01-03  0.353111 -0.410507 -0.453909  0.894343
2013-01-04  0.058367 -0.714148 -1.612650 -0.612193
2013-01-05 -0.801479  0.929410  0.750529  0.726869

In [62]:
df['A']

2013-01-01   -0.196382
2013-01-02   -1.094411
2013-01-03    0.353111
2013-01-04    0.058367
2013-01-05   -0.801479
2013-01-06   -0.438539
Freq: D, Name: A, dtype: float64

In [10]:
df.loc[dates[0]]

A   -0.787297
B    1.061876
C   -0.264260
D    1.049910
Name: 2013-01-01 00:00:00, dtype: float64

In [11]:
df.ix(:, )

A         B         C         D
2013-01-01 -0.787297  1.061876 -0.264260  1.049910
2013-01-02 -0.108800 -0.044183 -0.657105  0.891762
2013-01-03 -0.294857 -0.870832 -0.669630 -0.763743
2013-01-04  1.502492 -0.755786 -0.963276 -1.335181
2013-01-05  1.478292  1.448394 -0.783916 -0.717962

In [35]:
mat = np.matrix([[1, np.nan], [3, 4]])
print mat

[[  1.  nan]
 [  3.   4.]]


In [20]:
print mat[:, 1]

[[2]
 [4]]


In [22]:
a = [1, 2, 3]
b = [1] * 3
np.dot(a, b)

6

In [24]:
np.empty(3)

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

In [36]:
mat[np.isnan(mat)] = 0
mat

matrix([[ 1.,  0.],
        [ 3.,  4.]])

In [59]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.hstack((a, b))
print c

[[1 4]
 [2 5]
 [3 6]]


In [58]:
c[:,0]

array([1, 2, 3])

In [22]:
x = np.array([3, 1, np.nan, 4])

np.argsort(x)

array([1, 0, 3, 2])

In [14]:
print np.nan is np.nan

True


In [6]:
mat = np.matrix([[1, 2], [3, 4]])
mean = np.matrix([-1, 1])
print "mat", mat
print "mean", mean
print mat - mean

mat [[1 2]
 [3 4]]
mean [[-1  1]]
[[2 1]
 [4 3]]


In [9]:
print np.dot(mat, mean.transpose())
print mat * mean.transpose()

[[1]
 [1]]
[[1]
 [1]]


In [ ]:
a = array([1, 2, 3])
b = array([3, 4, 5])
c = array([6, 7, 8])
print hstack((a, b, c))
print vstack((a, b, c))
print dstack((a, b, c))[0]

In [4]:
def reject_outliers(data, m=2):
    return data[abs(data - np.mean(data)) < m * np.std(data)]

mat = np.matrix([[1, 10000], [3, 4]])

reject_outliers(mat)

matrix([[    1, 10000,     3,     4]])