## Pandas Basic

[10min Tutorial](http://pandas.pydata.org/pandas-docs/stable/10min.html)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dates = pd.date_range('20130101', periods=6)
print dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [9]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01 -1.237675 -1.077546  1.438019 -1.686684
2013-01-02 -1.600087 -0.173874 -1.218521  0.934975
2013-01-03 -2.318397 -1.245194 -0.953699 -1.502443
2013-01-04 -0.888818 -0.149619  0.658928  0.004189
2013-01-05  0.528069  0.482251 -0.458116  1.815285
2013-01-06  0.846226  0.766148  1.142742  0.429922

In [8]:
print df.shape

(6, 4)


In [62]:
df['A']

2013-01-01   -0.196382
2013-01-02   -1.094411
2013-01-03    0.353111
2013-01-04    0.058367
2013-01-05   -0.801479
2013-01-06   -0.438539
Freq: D, Name: A, dtype: float64

In [19]:
df.loc[dates[0]]

A   -1.237675
B   -1.077546
C    1.438019
D   -1.686684
Name: 2013-01-01 00:00:00, dtype: float64

In [31]:
df.ix[[True, False, True],:]

A         B         C         D
2013-01-01 -1.237675 -1.077546  1.438019 -1.686684
2013-01-03 -2.318397 -1.245194 -0.953699 -1.502443

In [64]:
a = df.ix[[True, False, True],:].values
print a
print type(a)

[[-1.23767544 -1.07754587  1.43801917 -1.68668392]
 [-2.31839726 -1.24519389 -0.95369937 -1.5024426 ]]
<type 'numpy.ndarray'>


In [53]:
a = [True, False]
print a
print np.invert(a)

[True, False]
[False  True]


In [35]:
mat = np.matrix([[1, np.nan], [3, 4]])
print mat

[[  1.  nan]
 [  3.   4.]]


In [20]:
print mat[:, 1]

[[2]
 [4]]


In [22]:
a = [1, 2, 3]
b = [1] * 3
np.dot(a, b)

6

In [24]:
np.empty(3)

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323])

In [36]:
mat[np.isnan(mat)] = 0
mat

matrix([[ 1.,  0.],
        [ 3.,  4.]])

In [59]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.hstack((a, b))
print c

[[1 4]
 [2 5]
 [3 6]]


In [58]:
c[:,0]

array([1, 2, 3])

In [22]:
x = np.array([3, 1, np.nan, 4])

np.argsort(x)

array([1, 0, 3, 2])

In [14]:
print np.nan is np.nan

True


In [6]:
mat = np.matrix([[1, 2], [3, 4]])
mean = np.matrix([-1, 1])
print "mat", mat
print "mean", mean
print mat - mean

mat [[1 2]
 [3 4]]
mean [[-1  1]]
[[2 1]
 [4 3]]


In [9]:
print np.dot(mat, mean.transpose())
print mat * mean.transpose()

[[1]
 [1]]
[[1]
 [1]]


In [ ]:
a = array([1, 2, 3])
b = array([3, 4, 5])
c = array([6, 7, 8])
print hstack((a, b, c))
print vstack((a, b, c))
print dstack((a, b, c))[0]

## HW4

K-means++ notes.

In [1]:
np.zeros((2, 3, 2))

NameError: name 'np' is not defined

In [4]:
np.inf

inf

In [5]:
np.random.randint(0, 9, 25)

array([0, 8, 5, 3, 6, 7, 6, 4, 0, 0, 2, 1, 7, 2, 3, 5, 4, 5, 8, 7, 1, 0, 5,
       8, 7])

In [11]:
from numpy.linalg import norm
print norm(np.array([1,2])-np.array([5,2]))

4.0


In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
[k*2 for k in range(5)]

[0, 2, 4, 6, 8]

### np.random.choice

What is replacement?
https://www.ma.utexas.edu/users/parker/sampling/repl.htm

In [24]:
x = np.random.choice([1, 2, 3, 4, 5],1, replace=False, p=[0.1, 0, 0.3, 0.6, 0])
[y] = np.random.choice([1, 2, 3, 4, 5],1, replace=False, p=[0.1, 0, 0.3, 0.6, 0])
print x, y

[3] 1


In [18]:
np.square([1,2,3])

array([1, 4, 9])

In [43]:
dict = {'Name': 'Zara', 'Age': 7}
print "Value : %s" %  dict.items()
print dict.keys()

Value : [('Age', 7), ('Name', 'Zara')]
['Age', 'Name']


In [30]:
np.argmin([1,2,3,-1])

3

In [39]:
a = [] * 10
print a

[]


In [42]:
data = [[1,2], [3,2]]
np.average(data, axis=0)

array([ 2.,  2.])

In [56]:
a = np.array([1,2,3,4])
a_sum = float(np.sum(a))
print a/a_sum

[ 0.1  0.2  0.3  0.4]


In [27]:
rdd = sc.parallelize([(1,np.array([2,3,4])), (2,np.array([4,1,3])), (1,np.array([1,1,0])), (1,np.array([2,3,4])) ])
#rdd.flatMapValues(lambda x: iter(x)).collect()
#rdd.map(lambda (key,value): (value, key)).collect()
print rdd.collect()
#new_points_rdd = rdd.reduceByKey(lambda x, y: (x+y)/float(2))
print rdd.collectAsMap()

[(1, array([2, 3, 4])), (2, array([4, 1, 3])), (1, array([1, 1, 0])), (1, array([2, 3, 4]))]
{1: array([2, 3, 4]), 2: array([4, 1, 3])}


In [11]:
a = np.array([[1,2,3],[3,4,5]])
b = np.matrix(a)
print b
print np.sum(b, axis=1)[0]
print b[0]

[[1 2 3]
 [3 4 5]]
[[6]]
[[1 2 3]]
